serenity-js/serenity-js

- package.json
- src/serenity-cucumber/webdriver_synchroniser.ts
Match syncronized steps with the contract cucumber expects. es6 generators accepted by cucumber are still not supported (#9)
> fix(cucumber): Support callback style step definitions (fixes #8)

- package.json
- spec/mocha.opts
- spec/transpiler.js
Istanbul wasn't instrumenting properly files not required by specs and they were omitted in coverage reports.
[webdriver_synchroniser.ts](https://github.com/jan-molak/serenity-js/blob/master/src/serenity-cucumber/webdriver_synchroniser.ts) for instance.
Also now I know that webdriver_synchroniser is not plugged into cucumber integration tests and will fix it with next PR.
> Fix coverage reporting

- package.json
- src/serenity-cucumber/webdriver_synchroniser.ts
Closes #9 
Adds integration tests for the following cucumber integration use cases: passing, failing and pending steps with respective sync, callback, promise and generator interfaces
> Add support for generator steps

- package.json
- packages/serenity-js.cucumber-2/package.json
- packages/serenity-js/package.json
Update the node version of package.json with >= 6.9.0.
It will make the Serenity JS work with the last node v6.10.0.
affects: serenity-js.cucumber-2, serenity-js
> fix(node version): update the node version with >= 6.9.0

- book/from-scripts-to-serenity/writing-what-you-would-like-to-read.md
Fixed a broken Hyper link:
This https://github.com/jan-molak/serenity-js/tree/master/spec/serenity-protractor/screenplay/interactions
gets a 404.
> Fixed broken link

- book/mocha/readme.md
- book/overview/configuration.md
- book/overview/mocha.md
- book/overview/retrofitting.md
Fixed broken links in retrofitting.html
The page http://serenity-js.org/overview/retrofitting.html had four non working links:
1. cucumberOpts
2. mochaOpts
3. serenity-mocha
4. serenity-cucumber
Fixed broken link, fixed copy&paste mistyping in overview/configuration.md.
> updated documentation

- packages/protractor/spec/screenplay/interactions/Clear.spec.ts
- packages/protractor/src/screenplay/interactions/Clear.ts
I found that Clear.theValueOf didn't have the ability to handle a empty input field, This small change should handle that
> Add ability to clear empty input field

- packages/rest/src/screenplay/interactions/ChangeApiConfig.ts
fixed typo in Setting a header for all subsequent requests example
> docs(rest): fixed typo in example

- examples/protractor-jasmine-todomvc/package.json
Jasmine dependency is needed in order to run tests in protractor-jasmine-todomvc folder, otherwise ```npm test```: command will fail.
I added current version of jasmine to package.json and tests can be executed without problem
> chore: add needed jasmine dependency

- CONTRIBUTING.md
I decided to create a file with a link to just keep it simple. Also, some links (e.g. `runtime dependencies`) do not work in markdown format, so we better just point people to the site.
> docs(contributing.md): added CONTRIBUTING.md to the root folder

- packages/jasmine/spec/adapter/JasmineAdapter.spec.ts
- packages/jasmine/src/adapter/JasmineAdapter.ts
- packages/jasmine/src/adapter/JasmineConfig.ts
When using Serenity/Jasmine, sometimes you might want to add existing third party reporters that are not "serenity standard" but, since you don't have access to the jasmine runner object, you cannot do `jasmine.addReporter(reporter)` in the protractor.conf file.
One practical example is using [ReportPortal's agent for Jasmine](https://github.com/reportportal/agent-js-jasmine), which provides all you need to send test executions to your [ReportPortal](https://reportportal.io/) instance seamlessly.
Assuming you have a reportportal config file called `reportportalConf.js` (see https://github.com/reportportal/agent-js-jasmine#protractor-integration), add the following chunks to your protractor.conf file:
```
const AgentJasmine = require('@reportportal/agent-js-jasmine')
const agent = new …
```
> feat: support additional reporters

- documentation/website/src/handbook-toc.yml
- documentation/website/src/handbook/integration/upgrading-to-serenity-js-3.md
added a migration guide page with coming soon footer and link to GitHub migration guide issue, added
the page to the handbook toc
#re 1157
@jan-molak: According to https://github.com/serenity-js/serenity-js/pull/1195 this would be the PR for master.
> docs(migration guide): added a migration guide page

- .github/renovate.json
- https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release.
> Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository,
> as they would need to generate a SHA-1 collision for a valid Git object payload.
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
- https://github.com/renovatebot/.github/blob/b0c3aa85ef2bb242580f20b02b380ca532b4ce17/default.json#L13
> chore: renovate bot setting to pin actions to a full length commit SHA

- packages/core/src/screenplay/Activity.ts
Thanks to @viper3400 for reporting the issue!
<a href="https://gitpod.io/#https://github.com/serenity-js/serenity-js/pull/1313"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(serenity-bdd): correct detection of invocation location for internal code

- packages/jasmine/spec/adapter/FakeJasmineRunner.ts
- packages/jasmine/src/adapter/JasmineAdapter.ts
When using Serenity/JS v3.0.0-rc.32 with Jasmine, some annoying warnings are shown:
```
[wdio-chrome-hubtype] [0-0] DEPRECATION: jasmine#addSpecFiles is deprecated. Use jasmine#addMatchingSpecFiles instead.
[wdio-chrome-hubtype] [0-0]     at <Jasmine>
[wdio-chrome-hubtype] [0-0]     at Jasmine.addSpecFiles (/home/lolo/code/hubtype-qa/acceptance/node_modules/jasmine/lib/jasmine.js:396:12)
[wdio-chrome-hubtype] [0-0]     at JasmineAdapter.loadSpecs (/home/lolo/code/hubtype-qa/acceptance/node_modules/@serenity-js/jasmine/src/adapter/JasmineAdapter.ts:107:21)
[wdio-chrome-hubtype] [0-0]     at JasmineAdapter.load (/home/lolo/code/hubtype-qa/acceptance/node_modules/@serenity-js/jasmine/src/adapter/JasmineAdapter.ts:90:20)
[wdio-chrome-hubtype] [0-0]     at WebdriverIOFrameworkAdapter.init …
```
> fix(jasmine): remove warn jasmine#addSpecFiles

- packages/core/spec/screenplay/QuestionAdapter.spec.ts
- packages/core/src/screenplay/Activity.ts
- packages/core/src/screenplay/Question.ts
- packages/web/src/screenplay/interactions/ExecuteScript.ts
Closes #1344
<a href="https://gitpod.io/#https://github.com/serenity-js/serenity-js/pull/1350"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix(core):  allow proxying location and description fields by `QuestionAdapter`

- documentation/serenity-js.org/blog/2022-08-12-upgrading-to-serenity-js-3.md
Missing pharenteses in `notes<MyNotes>().set()` example.
> Missing pharenteses in serenity-js v3 upgrade documentation

- packages/playwright-test/src/api/test-api.ts
Since the ability to PerformActivitiesAsPlaywrightSteps was instantiated in the `actors` fixture, overriding this fixture could have affected the Playwright HTML reporter. This change ensures that the ability is correctly attached even if a custom cast is used.
> fix(playwright-test): preserve Playwright Test-specific reporting when overriding actors

- packages/core/spec/screenplay/Actor.spec.ts
- packages/core/src/events/EmitsDomainEvents.ts
- packages/core/src/screenplay/Actor.ts
- packages/core/src/screenplay/time/TellsTime.ts
- packages/core/src/screenplay/time/index.ts
- packages/core/src/stage/StageManager.ts
It's now possible for your custom Interactions and Questions to retrieve the current wall clock time directly from the actor via `actor.currentTime()`
> feat(core): actors can tell the current time

- documentation/serenity-js.org/docusaurus.config.js
- packages/serenity-bdd/spec/cli/io/axiosClient.spec.ts
- packages/serenity-bdd/spec/cli/io/dummy.ca
- packages/serenity-bdd/src/cli/io/axiosClient.ts
HTTP Proxy Agent v7 changed its public API, so the Serenity BDD downloader had to be updated to reflect that
Related tickets: closes #1795
> fix(serenity-bdd): corrected downloading Serenity BDD jar using HTTP Proxy Agent

- packages/core/spec/model/CorrelationId.spec.ts
- packages/core/src/model/CorrelationId.ts
In BrowserStack, iOS window handles contain the `.` character. This causes the `CorrelationId` constructor to throw, since it checks against a regex that does not allow the `.` character.
**From BrowserStack console:**
**Serenity + Webdriver + Mocha log:**
```
[0-0] 2023-08-17T16:56:44.226Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2023-08-17T16:56:44.228Z INFO webdriver: [GET] https://hub-cloud.browserstack.com/wd/hub/session/5f384ebe43cedc180430b80f67325c9829dac1a8/window
[0-0] 2023-08-17T16:56:44.236Z INFO webdriver: RESULT Test: *********
[0-0] 2023-08-17T16:56:44.386Z INFO webdriver: RESULT 3202.1
[0-0] Error in "*********"
Error: CorrelationId should either be a Cuid or match pattern /^[\dA-Za-z-]+$/
at ensure ([[redacted]]/node_modules/tiny-types/src/ensure.ts:31:15)
at new …
```
> fix(core): support iOS window handles in CorrelationId

- documentation/serenity-js.org/docs/design/screenplay-pattern.mdx
- documentation/serenity-js.org/docs/getting-started/installation.mdx
- documentation/serenity-js.org/docs/getting-started/serenity-js-with-playwright-test.mdx
- documentation/serenity-js.org/docs/getting-started/serenity-js-with-protractor.mdx
- documentation/serenity-js.org/docs/getting-started/serenity-js-with-webdriverio.mdx
- documentation/serenity-js.org/docs/integration/gitlab-ci.mdx
- documentation/serenity-js.org/docs/reporting/serenity-bdd-reporter.mdx
- documentation/serenity-js.org/docs/test-runners/cucumber.mdx
- documentation/serenity-js.org/docs/test-runners/jasmine.mdx
- documentation/serenity-js.org/docs/test-runners/mocha.mdx
- documentation/serenity-js.org/docs/test-runners/playwright-test.mdx
- documentation/serenity-js.org/docs/test-runners/protractor.mdx
- documentation/serenity-js.org/docs/test-runners/webdriverio.mdx
- documentation/serenity-js.org/docusaurus.config.js
- documentation/serenity-js.org/package.json
- package-lock.json
- packages/assertions/README.md
- packages/console-reporter/README.md
- packages/core/README.md
- packages/cucumber/README.md
- packages/jasmine/README.md
- packages/local-server/README.md
- packages/mocha/README.md
- packages/playwright-test/README.md
- packages/playwright/README.md
- packages/protractor/README.md
- packages/rest/README.md
- packages/serenity-bdd/README.md
- packages/web/README.md
- packages/webdriverio/README.md
Windows terminal doesn't support Bash brace expansion, which means that developers using Windows might have found the installation instructions confusing.
This change makes installation instructions work across macOS, Linux, and Windows.
Related tickets: #1915
<a href="https://gitpod.io/#https://github.com/serenity-js/serenity-js/pull/1916"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs(website): installation instructions are now more friendly to Windows users

- documentation/serenity-js.org/docs/web-testing/page-element-query-language.md
- documentation/serenity-js.org/docs/web-testing/page-objects-pattern.mdx
Improved the examples mentioned in the documentation of the `Page Element Query Language` Section inside the `Web Testing` Module. Improvements include:
- Adding missing imports in examples
- Documentation typo fixes
- Fixing some assertion checks in the examples
> docs(web): fixes some assertions, documentation typos, and adds missing imports

- documentation/serenity-js.org/src/pages/index.tsx
I perused the front page and noticed a missing space.
> docs(website): add missing space on home page

- documentation/serenity-js.org/docs/reporting/domain-events.mdx
Fixes a small typo in documentation.
> docs(core): fixed typo

- integration/web-specs/spec/screenplay/questions/Attribute.spec.ts
- packages/web/src/screenplay/questions/Attribute.ts
Some attributes, like the anchor "download" attribute, do not have a value, so it's more semantically correct to check if they're present rather than that they have an empty value
> feat(web): actors can now check if an HTML element attribute is present

- documentation/serenity-js.org/src/pages/contributing.mdx
Hi, I have seem to have a different approach regarding commits, where I create more of them with parts of my work, instead of one for an entire functionality. When I have seen the patchnotes for 3.19, I noticed it'd be quite confusing to see patch note with "reverting to previous functionality"
That's why I added a note for that in the docs 😄 
@jan-molak
> Adding a note about commit messages going into patch notes 

- packages/core/spec/FakeFS.ts
- packages/core/spec/io/FileSystem.spec.ts
- packages/core/spec/io/Version.spec.ts
- packages/core/src/io/FileSystem.ts
- packages/core/src/io/Version.ts
- packages/core/src/io/index.ts
- packages/core/src/io/loader/ModuleLoader.ts
- packages/core/src/io/loader/index.ts
Being able to directly read files from the file system in crew members should enable services like the ConsoleReporter to display code snippets and will enable refactoring the artifact handling mechanism in the SerenityBDDReporter
Related tickets: re #2244
> feat(core): simplified reading and writing files in CrewMembers using the FileSystem

- documentation/serenity-js.org/docs/design/screenplay-pattern.mdx
Was not clear that certain Abilities are defaulted when using `actorCalled`. It was being missed when skimming page, so made explicit.
> docs(examples): clarified default Abilities

- .github/workflows/main.yaml
- integration/playwright-web/package.json
- integration/protractor-web/package.json
- integration/webdriverio-web/package.json
- packages/serenity-bdd/package.json
This change should simplify overall setup experience for most of the cases by eleminating the need to run "serenity-bdd update" manually. Default version of Serenity BDD will be saved into default directory and will be included into files under the default path of the package and published to NPM registry.
This change does not affect current customization capabilities in any way, it's still possible to set custom cache directory or set specific version of Serenity BDD.
Related tickets: #2560
> feat(serenity-bdd): include Serenity BDD CLI jar file into files of the published package

- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/SerenityBDDReporter/describing_scene.spec.ts
- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/SerenityBDDReporter/reporting_business_rules.spec.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/scene-sequence/transformations/scenarioParametersOf.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/backgroundOf.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/businessRuleOf.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/descriptionOf.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/featureNarrativeOf.ts
All the parameters, business rules, feature narratives, and similar descriptions now have HTML entities correctly escaped to prevent formatting errors and potential script injection attacks. Thanks to @softwaretestingcentre for identifying the issue!
Closes #2879
> fix(serenity-bdd): escape HTML entities in scenario parameter descriptions

- .github/workflows/chore-delete-old-workflows.yaml
Potential fix for [https://github.com/serenity-js/serenity-js/security/code-scanning/66](https://github.com/serenity-js/serenity-js/security/code-scanning/66)
To fix the issue, add a `permissions` block to the workflow to explicitly define the least privileges required for the task. Since the workflow deletes old workflow runs, it likely requires `contents: read` to access repository contents and `actions: write` to delete workflow runs. This ensures that the `GITHUB_TOKEN` has only the necessary permissions, reducing the risk of unintended actions.
The `permissions` block should be added at the root level of the workflow to apply to all jobs, as there is only one job in this workflow. Alternatively, it could be added specifically to the `delete_old_workflows` job.
---
_Suggested fixes …
> Potential fix for code scanning alert no. 66: Workflow does not contain permissions

- .github/workflows/main.yaml
- packages/core/spec/model/Tag.spec.ts
- packages/core/src/events/SceneTagged.ts
- packages/core/src/instance.ts
- packages/core/src/model/tags/Tag.ts
- packages/core/src/model/tags/Tags.ts
Previously, a serialised `Tag` object would be deserialised by calling `Tag.fromJSON`. This method would then internally call the appropriate tag constructor function. While this approach works, it creates a sub-optimal import graph as Tag relies on all the tags that implement it, and in turn, all the tags rely on Tag. This import graph confuses some TypeScript transpilers and requires simplifying.
In this PR, I moved the `toJSON` method from `Tag` to `Tags` to simplify the import graph.
> fix(core): internal - refactored Tag deserialiser to simplify the import graph

- packages/core/src/screenplay/questions/tag-functions.ts
This change addresses a typo made in the docs explaining the tagged template literal `q`.
> docs(tag-functions): fixed typo

- .github/renovate.json
- integration/protractor-web/protractor.conf.js
- integration/web-specs/spec/screenplay/models/PageElement.located.ByRole.spec.ts
- integration/web-specs/static/screenplay/models/page-element/by_role.html
- packages/core/package.json
- packages/playwright/src/screenplay/models/locators/PlaywrightLocator.ts
- packages/web/src/screenplay/models/selectors/By.ts
- packages/web/src/screenplay/models/selectors/ByRole.ts
- packages/web/src/screenplay/models/selectors/index.ts
- packages/webdriverio-8/src/screenplay/models/locators/WebdriverIOLocator.ts
- packages/webdriverio/src/screenplay/models/locators/WebdriverIOLocator.ts
- pnpm-lock.yaml
In the new selector `By.role(role, options)`:
- all the `options` are fully supported by Playwright - name can be expressed as `string` or `RegEx`, additional options for selecting elements that are `pressed`, `checked`, `disabled`, `expanded`, and so on
- only the `name` option is supported by WebdriverIO
`By.role` is not supported by Protractor.
> feat(web): support for identifying page elements by their ARIA role and name
