- spec/cookbook/html_form.recipe.ts
- src/serenity-protractor/screenplay/abilities/browse_the_web.ts
- src/serenity-protractor/screenplay/interactions/execute.ts
- src/serenity-protractor/screenplay/interactions/index.ts
I was in need to use execute script from Protractor API so implemented the missing interaction..
> Add execute script interaction

- packages/serenity-js/spec/cookbook/alerts.recipe.ts
- packages/serenity-js/spec/cookbook/apps/alerts.html
- packages/serenity-js/src/serenity-protractor/screenplay/abilities/browse_the_web.ts
- packages/serenity-js/src/serenity-protractor/screenplay/interactions/alert.ts
- packages/serenity-js/src/serenity-protractor/screenplay/interactions/waitForAlert.ts
feat: support for alerts accept and cancel (not able to run specs yet due to unexplained run-time errors
> #65: Adding Support for Alerts to serenity-js

- packages/serenity-js/spec/cookbook/content.recipe.ts
- packages/serenity-js/src/serenity-protractor/screenplay/abilities/browse_the_web.ts
- packages/serenity-js/src/serenity-protractor/screenplay/questions/website.ts
Addresses feature request #111
> Added ability to ask questions about the url

- packages/rest/.gitignore
- packages/rest/.npmignore
- packages/rest/LICENSE.md
- packages/rest/NOTICE.md
- packages/rest/README.md
- packages/rest/mocha.opts
- packages/rest/package.json
- packages/rest/spec/expect.ts
- packages/rest/spec/screenplay/abilities/call_an_api.spec.ts
- packages/rest/spec/screenplay/interactions/delete.spec.ts
- packages/rest/spec/screenplay/interactions/get.spec.ts
- packages/rest/spec/screenplay/interactions/post.spec.ts
- packages/rest/spec/screenplay/interactions/put.spec.ts
- packages/rest/src/index.ts
- packages/rest/src/screenplay/abilities/call_an_api.ts
- packages/rest/src/screenplay/abilities/index.ts
- packages/rest/src/screenplay/index.ts
- packages/rest/src/screenplay/interactions/delete.ts
- packages/rest/src/screenplay/interactions/get.ts
- packages/rest/src/screenplay/interactions/index.ts
- packages/rest/src/screenplay/interactions/post.ts
- packages/rest/src/screenplay/interactions/put.ts
- packages/rest/src/screenplay/questions/index.ts
- packages/rest/src/screenplay/questions/last_response.ts
- packages/rest/tsconfig.json
- packages/serenity-js/spec/protractor-cookbook.conf.js
Initial rest package commit with the following:
Ability CallAnApi
Interactions: Get Put Post Delete
Questions: LastRequest
> Init rest package

- packages/serenity-js/src/serenity-protractor/stage/photographer.ts
This PR is a left over piece of work to fix a problem that was [discussed in #65](https://github.com/jan-molak/serenity-js/issues/65#issuecomment-309224334) in relation to UnexpectedAlertOpenError breaking the screenshot code e.g. when exception is thrown in Photographer, we ignore it the same way as WebDriver's invalid session.
> #148 feat: skip photo attempt under UnexpectedAlertOpenError

- package.json
> chore(package): update sinon to version 4.4.6

- book/from-scripts-to-serenity/writing-what-you-would-like-to-read.md
- docs/from-scripts-to-serenity-getting-started-writing-what-you-would-like-to-read.md
- examples/todomvc-model/src/user_interface/todo_list.ts
There is no id on that web element, and it was breaking the tutorial and examples.
> Fixing the locator for 'What needs to be done?' input box

- packages/core/package-lock.json
- packages/core/package.json
- packages/cucumber-2/package-lock.json
- packages/cucumber-2/package.json
- packages/cucumber/package-lock.json
- packages/rest/package-lock.json
- packages/serenity-js/package-lock.json
- packages/serenity-js/package.json
Manually updated moment and lodash to the latest version.
Also ran npm audit fix at the root to automatically update
some other vulnerable dependencies.
> Update vulnerable dependencies

- documentation/website/src/community/events-and-articles.md
got rid of the word 'header' in anchor link id
> Updated my anchor link slightly

- documentation/website/src/community/events-and-articles.md
An overview of my introduction to Serenity-JS and the Screenplay pattern and how it helped me to utilise SOLID principles in my test automation. Links to handbook and repo.
> Added Serenity-JS article from SureSoft Limited

- docs/from-scripts-to-serenity-introduction-speaking-the-right-language.md
Great document! Just making a few minor improvements.
> Removed a superfluous word and fixed the Martin Fowler link

- packages/protractor/spec/screenplay/interactions/RightClick.spec.ts
- packages/protractor/src/screenplay/interactions/RightClick.ts
- packages/protractor/src/screenplay/interactions/index.ts
> feat(protractor): implemented right click

- .github/workflows/build.yaml
- examples/protractor-cucumber/package.json
- examples/protractor-cucumber/protractor.conf.js
- examples/protractor-jasmine-todomvc/package.json
- examples/protractor-jasmine-todomvc/protractor.conf.js
- examples/protractor-jasmine/package.json
- examples/protractor-jasmine/protractor.conf.js
- examples/protractor-mocha/package.json
- examples/protractor-mocha/protractor.conf.js
- integration/protractor-cucumber/examples/protractor.conf.js
- integration/protractor-cucumber/package.json
- integration/protractor-jasmine/examples/protractor.conf.js
- integration/protractor-jasmine/package.json
- integration/protractor-mocha/examples/protractor.conf.js
- integration/protractor-mocha/package.json
- package-lock.json
- package.json
- packages/core/src/stage/StageManager.ts
- packages/protractor/package.json
- packages/protractor/spec/protractor.conf.js
- packages/protractor/spec/screenplay/interactions/Clear.spec.ts
- packages/protractor/src/screenplay/abilities/BrowseTheWeb.ts
- packages/protractor/src/screenplay/interactions/Clear.ts
- packages/protractor/src/screenplay/interactions/Select.ts
- packages/protractor/src/screenplay/questions/Attribute.ts
- packages/protractor/src/screenplay/questions/CSSClasses.ts
- packages/protractor/src/screenplay/questions/Selected.ts
- packages/protractor/src/screenplay/questions/Value.ts
- protractor.conf.js
- https://bugs.chromium.org/p/chromium/issues/detail?id=1205107&start=300
- angular/protractor#5519
> Support for Chrome 91

- packages/webdriverio/spec/fixtures.ts
- packages/webdriverio/spec/screenplay/interactions/Scroll.spec.ts
- packages/webdriverio/src/screenplay/interactions/Scroll.ts
- packages/webdriverio/src/screenplay/interactions/index.ts
As I've written in the Gitter chat please consider to merge the ```Scroll``` interaction.
> feat(webdriverio): implemented Scroll interaction

- integration/web/static/screenplay/interactions/scroll/long_page.html
- integration/webdriverio-jasmine/spec/failing_scenario.spec.ts
- integration/webdriverio-jasmine/spec/passing_scenario.spec.ts
- integration/webdriverio-jasmine/spec/using_grep.spec.ts
- packages/cucumber/spec/cli/CucumberCLIAdapter.spec.ts
- packages/web/src/stage/crew/photographer/strategies/PhotoTakingStrategy.ts
Hi @jan-molak, I had some troubles and ran into time-outs on my Windows machine.
> fix(integration): adjusted some test time-outs

- documentation/website/src/handbook/reporting/serenity-bdd-reporter.md
Getting "Not Found - GET https://registry.npmjs.org/serenity-bdd - Not found" for "npx serenity-bdd update" but "npx @serenity-js/serenity-bdd update" works.
> add scope to "serenity-bdd" for npx commands

- documentation/website/src/handbook/design/screenplay-pattern.md
- documentation/website/src/handbook/thinking-in-serenity-js/hello-serenity-js.md
close #1166
@jan-molak , I started to with migration of the docs. I suggest to do this in an iterative way, starting with #1166 and this PR. The overall process will be tracked in #1157.
> docs(screenplay-pattern.md): migrated documentation to Serenity/JS 3

- documentation/website/src/handbook/integration/serenityjs-and-cucumber.md
- documentation/website/src/handbook/integration/serenityjs-and-jasmine.md
- documentation/website/src/handbook/integration/serenityjs-and-mocha.md
- documentation/website/src/handbook/integration/serenityjs-and-webdriverio.md
Updated section for usage with Cucumber, Jasmine, Mocha. Added new page for intergrating with
WebdriverIO
close #1192
> docs(integration guide): updated section integration guide to match Serenity/JS 3.x

- packages/web/package.json
> chore(@serenity-js/web): add npm version 8 to allowed versions

- .github/workflows/main.yaml
- integration/cucumber-8/.gitignore
- integration/cucumber-8/.mocharc.yml
- integration/cucumber-8/package.json
- integration/cucumber-8/src/register-cucumber.ts
- integration/cucumber-8/src/step_definitions/ambiguous.steps.ts
- integration/cucumber-8/src/step_definitions/common.steps.ts
- integration/cucumber-8/src/step_definitions/hooks.steps.ts
- integration/cucumber-8/src/step_definitions/retry.steps.ts
- integration/cucumber-8/src/step_definitions/rules.steps.ts
- integration/cucumber-8/src/step_definitions/screenplay.steps.ts
- integration/cucumber-8/src/step_definitions/skip_hook.ts
- integration/cucumber-8/src/step_definitions/wip_hook.steps.ts
- integration/cucumber-8/src/support/Actors.ts
- integration/cucumber-8/src/support/configure_serenity.ts
- integration/cucumber-8/tsconfig.eslint.json
- integration/cucumber-8/tsconfig.json
- package.json
- packages/cucumber/package.json
- packages/cucumber/spec/cli/CucumberCLIAdapter.spec.ts
- packages/cucumber/src/cli/CucumberCLIAdapter.ts
- packages/cucumber/src/listeners/messages/parser/CucumberMessagesParser.ts
- packages/cucumber/src/listeners/messages/types/cucumber.ts
> Serenity/JS 3.0 - Support for Cucumber 8

- .github/workflows/main-detect-changes.yaml
- .github/workflows/main.yaml
- documentation/serenity-js.org/src/css/custom.css
> chore(website): corrected CSS so that the logo displays properly in the API docs plus fix to website build

- .github/workflows/main.yaml
- .gitpod.yml
- .vscode/extensions.json
recommended extensions should make it easier for people to get started with the project
<a href="https://gitpod.io/#https://github.com/serenity-js/serenity-js/pull/1300"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci(gitpod): added a list of recommended VSCode extensions

- documentation/website/src/handbook/design/questions.md
Website.ts does not exist anymore
<a href="https://gitpod.io/#https://github.com/serenity-js/serenity-js/pull/1307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> (doc) remove reference to deleted file Website.ts

- integration/web-specs/spec/screenplay/models/Cookie.spec.ts
- packages/web/src/screenplay/models/Cookie.ts
> fix(web): support for setting cookies using async or partially async data

- integration/cucumber-8-javascript-api/src/step_definitions/named_hooks.steps.ts
- integration/cucumber-8-legacy-api/src/step_definitions/named_hooks.steps.ts
- integration/cucumber-specs/features/named_hooks.feature
- integration/cucumber-specs/spec/hooks.spec.ts
- integration/testing-tools/src/PickEvent.ts
- packages/cucumber/src/listeners/messages/parser/CucumberMessagesParser.ts
- packages/cucumber/src/listeners/messages/parser/TestStepFormatter.ts
- packages/cucumber/src/listeners/messages/types/cucumber.ts
> feat(cucumber): support reporting named hooks

- integration/web-specs/spec/screenplay/interactions/Wait.spec.ts
- packages/core/spec/screenplay/time/models/Scheduler.spec.ts
- packages/core/src/screenplay/time/abilities/ScheduleWork.ts
- packages/core/src/screenplay/time/models/Scheduler.ts
- packages/playwright-test/src/api/SerenityOptions.ts
- packages/playwright-test/src/api/test-api.ts
- packages/protractor/src/adapter/ProtractorFrameworkAdapter.ts
- packages/webdriverio/src/adapter/WebdriverIOFrameworkAdapter.ts
> fix(core): duration of Wait.for(..) can now exceed interactionTimeout

- .eslintrc.yml
- documentation/serenity-js.org/docs/design/screenplay-pattern.mdx
- documentation/serenity-js.org/docs/test-runners/cucumber.mdx
- documentation/serenity-js.org/docs/test-runners/jasmine.mdx
- documentation/serenity-js.org/docs/test-runners/mocha.mdx
- documentation/serenity-js.org/docs/test-runners/playwright-test.mdx
- documentation/serenity-js.org/docs/test-runners/protractor.mdx
- documentation/serenity-js.org/docs/test-runners/webdriverio.mdx
- documentation/serenity-js.org/src/theme/MDXComponents.ts
as suggested by @christian-bromann in webdriverio/webdriverio#10356
> docs(website): removed duplicate imports

- .github/workflows/main-detect-changes.yaml
- .github/workflows/main.yaml
since its defaults have changed
> ci(github): adjusted configuration of tj-actions/changed-files

- documentation/serenity-js.org/docs/web-testing/your-first-web-scenario.mdx
As I've been following along with [Your first web scenario](https://serenity-js.org/handbook/web-testing/your-first-web-scenario/), I've been trying to squash any typos I see along the way.
Serenity/JS seems great so far!
Let me know if you have any feedback so far!
> Proofread first web scenario

- .github/ISSUE_TEMPLATE/bug_report.yml
added yarn list to Serenity/JS versions textarea and moved it to the bottom of the template
> chore(github): changed bug report template

- packages/playwright/src/PlaywrightOptions.ts
- packages/playwright/src/screenplay/abilities/BrowseTheWebWithPlaywright.ts
> docs(playwright): documentated how to configure Playwright browser context options

- packages/core/src/screenplay/Actor.ts
- packages/core/src/screenplay/artifacts/CollectsArtifacts.ts
> docs(core): documented actor.collect API

- integration/web-specs/spec/screenplay/interactions/Enter.spec.ts
- packages/core/spec/screenplay/questions/Masked.spec.ts
- packages/core/src/screenplay/questions/Masked.ts
- packages/core/src/screenplay/questions/index.ts
- packages/rest/src/screenplay/interactions/ChangeApiConfig.ts
- packages/web/src/screenplay/interactions/Enter.ts
implemented possibility to enter sensitive data not visible in the report
Related tickets: #2165
> feat(web): implemented possibility to enter sensitive data 

- packages/core/src/screenplay/questions/Masked.ts
Hi, while switching from my solution to typing sensitive data to Masked question, I noticed code example misses ending bracket 😄
> Fix "Masked" Question code example

- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/SerenityBDDReporter/tagging_scenarios.spec.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/tagOf.ts
> fix(serenity-bdd): fixed feature tag links for nested spec structures

- documentation/serenity-js.org/docs/test-runners/cucumber.mdx
Better that trying to tie a command line together.
> docs(website): switch to structured cucumber configuration

- documentation/serenity-js.org/docs/design/debugging.mdx
- documentation/serenity-js.org/docs/web-testing/page-element-query-language.md
- integration/web-specs/spec/screenplay/models/PageElement.spec.ts
- integration/web-specs/static/screenplay/models/page-element/outer_html.html
- package-lock.json
- package.json
- packages/cucumber/tsconfig.build.json
- packages/playwright/src/screenplay/models/PlaywrightPageElement.ts
- packages/protractor/src/screenplay/models/ProtractorPageElement.ts
- packages/web/src/screenplay/models/PageElement.ts
- packages/webdriverio/src/screenplay/models/WebdriverIOPageElement.ts
`PageElement.html()` returns the `outerHTML` content of the given PageElement, or each PageElement in a collection of PageElements to support [debugging of PEQL queries](/handbook/design/debugging/#inspecting-page-element-html).
CC @thirstybear
> feat(web): new method PageElement.html()

- .github/workflows/main.yaml
- package-lock.json
- package.json
Node 22 is an active LTS release as of 2024-10-29, see https://github.com/nodejs/release#release-schedule
> chore(github): build Serenity/JS using Node 22

- examples/cucumber-domain-level-testing/package.json
- examples/cucumber-reporting/package.json
- examples/cucumber-rest-api-level-testing/package.json
- examples/playwright-test-todomvc/package.json
- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/SerenityBDDReporter/dealing_with_out_of_order_events.spec.ts
- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/SerenityBDDReporter/reporting_activities.spec.ts
- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/snapshots/examples/issue-1162-scenario_with_interactions_in_before_all_hook.json
- packages/serenity-bdd/spec/stage/crew/serenity-bdd-reporter/snapshots/examples/scenario_with_interactions_in_before_and_after_hooks.json
- packages/serenity-bdd/src/cli/defaults.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/activityFinished.ts
- packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/activityStarted.ts
- pnpm-lock.yaml
> fix(serenity-bdd): correctly escape HTML entities in activity descriptions

- packages/webdriverio-8/src/screenplay/models/WebdriverIOBrowsingSession.ts
Instead of throwing an error like with windows closed by user action, WebdriverIO 8 started to return a null handle for windows closed by client-side JavaScript. This fix addresses this issue.
> fix(webdriverio-8): handle windows and tabs closed by JavaScript
